#-------------------------------------------- 
#------------ User Configuration ------------
#--------------------------------------------
wifi:
  # ssid:     !secret wifi_ssid5          # switch "!secret wifi_ssid5" to your wifi ssid
  # password: !secret wifi_password5      # switch "!secret wifi_password5" to your wifi password

# Switch this section based on your chip
esp8266:
  board: esp01_1m
  restore_from_flash: true
# esp32:
#   board: esp32doit-devkit-v1

substitutions:
  device_name:   "melachaminder-s31"      # access web UI using "device_name".local/ or it's IP
  friendly_name: "Melacha Minder S31"
  
  relay_1_gpio:       "GPIO12"          # Switch this section
  button_1_gpio:      "GPIO0"           # based on your chip
  built_in_led_gpio:  "GPIO13"
  led_inverted:       "true"

  relay_restore_mode:    "RESTORE_DEFAULT_ON"              # relay and led state on startup, change to ALWAYS_ON,
  inverted_shabbos_mode: "RESTORE_DEFAULT_OFF"     # to default relay on for Shabbos see esphome.io/components/switch/

  timezone: America/Chicago            # check format at en.wikipedia.org/wiki/List_of_tz_database_time_zones
  eretz_yisrael: "RESTORE_DEFAULT_OFF"  # switch to RESTORE_DEFAULT_ON if located in EY and do a one day Yom Tov

  latitude:  "42.01208717"            
  longitude: "-87.69967051"               
  
  min_offset_start: "-30"               # offset in minutes (on Shabbos start options are: -300 - 120, on end: -120 - 120)
  min_offset_end:   "0"                 # use negative number for an early offset (-30) and positive for a later offset

  deg_shabbos_starts: "-0.833"          # shkiah is at -0.833
  deg_shabbos_ends:   "-8.5"            # time based off Alter Rebbe www.chabad.org/3209349
  deg_tzeit:          "-6"

esphome:
  includes:
    - header-files/melachaminder_main.h

packages:
  # Local Packages saved in plugins folder
  # melacha_config:      !include plugins/melachaminder/melacha_config.yaml     # Required
  # plug_info:           !include plugins/melachaminder/plug_info.yaml          # Required
  # location_info:       !include plugins/melachaminder/location_info.yaml      # Required
  # optional_config:     !include plugins/melachaminder/optional_config.yaml    # Optional

  remote_package:
    url: https://github.com/jmarshak/melachaminder/
    ref: main                                                               # optional
    files: 
      - esphome/plugins/melachaminder/melacha_config.yaml                     # Required
      - esphome/plugins/melachaminder/plug_info.yaml                          # Required
      - esphome/plugins/melachaminder/location_info.yaml                      # Required
      - esphome/plugins/melachaminder/optional_config.yaml                    # Optional
    refresh: 1d                                                             # Optional